<center><h2 style="color:#0000ff; font-family:Georgia;"><b>DATA 645. Neural Networks and Deep Learning</b></h2>
<h2 style="color:#ff0000; font-family:'Calibri';">Module 3. Homework Lab</h2>
<h1 style="color:#9933cc; font-family:Arial;"><b>Tensor Operations<br></b></h1></center>

### Instructions:

Use numpy for all matrix and tensor operations.

Comment your code to explain what each step does.

Use print() statements to show results when appropriate.

### Exercise 1: Matrix Creation and Reshaping

1. Create a NumPy array with numbers from 1 to 12.

2. Reshape it into a 3×4 matrix.

3. Then reshape it into a 2×2×3 tensor.

### Exercise 2: Matrix Transposition and Dot Product

1. Create a random 3×2 matrix A and a random 2×3 matrix B.

2. Compute A × B using matrix multiplication.

3. Transpose matrix A and print it.

### Exercise 3: Broadcasting and Elementwise Operations

1. Create a 2×3 matrix of all ones.

2. Add a 1D array [1, 2, 3] to it using broadcasting.

3. Multiply the resulting matrix by 5.

### Exercise 4: Tensor Operations

1. Create a 3×3×3 tensor with random integers from 0 to 9.

2. Extract the second "slice" (i.e., second 3×3 matrix).

3. Compute the elementwise square of the tensor.

### Exercise 5: Tensor Product of 3D and 2D Tensors

1. Create a 3×2×2 tensor T1 with integer values from 1 to 12.

2. Create a 2×2 matrix T2 with integers from 1 to 4.

3. Compute the outer product (tensor product) of T1 and T2 using broadcasting so that the result is a 3×2×2×2×2 tensor.

4. Print the shape and one slice of the resulting tensor.

# 1.1 Create a NumPy array with numbers from 1 to 12.

In [13]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 1.2 Reshape it into a 3×4 matrix.

In [12]:
x_matrix = x.reshape(3,4)
print(x_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 1.3 Then reshape it into a 2×2×3 tensor.

In [11]:
x_3d = x_matrix.reshape(2,2,3)
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# 2.1 Create a random 3×2 matrix A and a random 2×3 matrix B.

In [25]:
# np.randint takes arguments for low, high, and size when generating random data structures.
A = np.random.randint(low=50, high=150, size=(3, 2))
print(A)
B = np.random.randint(low=0, high=12, size=(2, 3))
print(B)

[[102  61]
 [ 55 113]
 [ 62  74]]
[[ 1  3  3]
 [10  3  3]]


# 2.2 Compute A × B using matrix multiplication.

In [26]:
import tensorflow as tf
# Matrix multiplication multiplies rows of one matrix with columns of the other.
tf.matmul(A, B)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 712,  489,  489],
       [1185,  504,  504],
       [ 802,  408,  408]], dtype=int32)>

# 2.3 Transpose matrix A and print it.

In [28]:
# Transposing switches rows and columns 
A_transpose = tf.transpose(A)
print(A_transpose)

tf.Tensor(
[[102  55  62]
 [ 61 113  74]], shape=(2, 3), dtype=int32)


# 3.1 Create a 2×3 matrix of all ones.

In [29]:
uno_matrix = np.ones((2, 3))
print(uno_matrix)

[[1. 1. 1.]
 [1. 1. 1.]]


# 3.2 Add a 1D array [1, 2, 3] to it using broadcasting.

In [32]:
# Broadcasting an operation repeats a lower dimensional tensor across the additional dimension(s) of higher dimensional tensors.
array_1d = np.array([1,2,3])
brocast = uno_matrix + array_1d
print(brocast)

[[2. 3. 4.]
 [2. 3. 4.]]


# 3.3 Multiply the resulting matrix by 5.

In [34]:
# Conducting element-wise multiplication
mult = tf.multiply(brocast, 5)
print(mult)

tf.Tensor(
[[10. 15. 20.]
 [10. 15. 20.]], shape=(2, 3), dtype=float64)


# 4.1 Create a 3×3×3 tensor with random integers from 0 to 9.

In [36]:
# Assuming that "0 to 9" means "0 through 9", I am setting the upper parameter to 10 since it is the cutoff.
t_sor = np.random.randint(0, 10, size = (3, 3, 3))
print(t_sor)

[[[2 5 9]
  [6 4 3]
  [2 9 5]]

 [[2 8 6]
  [5 1 5]
  [9 7 8]]

 [[7 7 9]
  [2 9 9]
  [8 1 3]]]


# 4.2 Extract the second "slice" (i.e., second 3×3 matrix)

In [41]:
# Extracting slices is functionally similar to extracting from lists
x_tract = t_sor[1,:,:]
print(x_tract)

[[2 8 6]
 [5 1 5]
 [9 7 8]]


# 4.3 Compute the elementwise square of the tensor.

In [39]:
# The square operation conducts elementwise squaring.
sq_r = tf.square(x_tract)
print(sq_r)

tf.Tensor(
[[ 4 64 36]
 [25  1 25]
 [81 49 64]], shape=(3, 3), dtype=int32)


# 5.1 Create a 3×2×2 tensor T1 with integer values from 1 to 12.

In [40]:
T1 = np.random.randint(1, 13, size = (3, 2, 2))
print(T1)

[[[11  2]
  [11  4]]

 [[ 5  6]
  [ 9 11]]

 [[ 6  5]
  [11  8]]]


# 5.2 Create a 2×2 matrix T2 with integers from 1 to 4.

In [42]:
T2 = np.random.randint(1, 5, size = (2, 2))
print(T2)

[[1 1]
 [4 3]]


# 5.3 Compute the outer product (tensor product) of T1 and T2 using broadcasting so that the result is a 3×2×2×2×2 tensor.

In [52]:
T1_ex = T1[:, :, :, np.newaxis, np.newaxis]
T2_ex = T2[np.newaxis, np.newaxis, np.newaxis, :, :]
outer_pro = T1_ex * T2_ex

In [ ]:
# 5.4 Print the shape and one slice of the resulting tensor.

In [51]:
print(outer_pro.shape)
print(outer_pro[1])

(3, 2, 2, 2, 2)
[[[[ 5  5]
   [20 15]]

  [[ 6  6]
   [24 18]]]


 [[[ 9  9]
   [36 27]]

  [[11 11]
   [44 33]]]]
